import type { BifrostTask, TaskPriority, TaskStatus, TaskType, TaskWorkspaceResponse } from "@bifrost/contracts";
import { useEffect, useState } from "react";
import { createTask, getTaskWorkspace, updateTaskStatus } from "../../api/client";

export function TaskWorkspace({ accessToken }: { accessToken: string }) {
  const [data, setData] = useState<TaskWorkspaceResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const reload = async () => setData(await getTaskWorkspace(accessToken));
  useEffect(() => { void reload().catch((reason) => setError(messageFrom(reason))); }, [accessToken]);
  const run = async (action: () => Promise<unknown>, message: string) => { setError(null); setSuccess(null); try { await action(); await reload(); setSuccess(message); } catch (reason) { setError(messageFrom(reason)); throw reason; } };
  if (!data) return <WorkspaceState title="Laster oppgaver" detail="Henter dine aktive og fullførte oppgaver …" error={Boolean(error)} />;
  return <section className="flex-1 py-8"><div className="mb-7"><p className="text-sm text-cyan-300">Oppgaveflyt</p><h1 className="mt-1 text-3xl font-semibold">Oppgaver</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Alle kan følge og oppdatere egne oppgaver. Ledelse og logistikk kan opprette, tildele og se hele oversikten.</p></div>{error && <Banner tone="error">{error}</Banner>}{success && <Banner tone="success">{success}</Banner>}{data.canManageAll && <NewTask accessToken={accessToken} data={data} run={run} />}<TaskList title="Mine oppgaver" detail="Oppgaver som er tildelt deg" tasks={data.myTasks} accessToken={accessToken} run={run} editable />{data.canManageAll && <TaskList title="Alle oppgaver" detail="Samlet operativ oversikt" tasks={data.allTasks} accessToken={accessToken} run={run} />}</section>;
}

function NewTask({ accessToken, data, run }: { accessToken: string; data: TaskWorkspaceResponse; run: RunAction }) {
  const [type, setType] = useState<TaskType>("work"); const [saving, setSaving] = useState(false);
  return <form className={cardClass} onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); void run(() => createTask(accessToken, { title: String(form.get("title")), type, transportJobId: type === "transport" ? Number(form.get("transportJobId")) || null : null, status: String(form.get("status")) as TaskStatus, priority: Number(form.get("priority")) as TaskPriority, message: String(form.get("message") ?? "") || null, description: String(form.get("description")), assignedUserId: Number(form.get("assignedUserId")), dueAt: String(form.get("dueAt")) }), "Oppgaven er opprettet.").then(() => { event.currentTarget.reset(); setType("work"); }).catch(() => undefined).finally(() => setSaving(false)); }}><p className="text-sm text-cyan-300">Ny oppgave</p><h2 className="mt-1 text-xl font-semibold">Opprett og tildel</h2><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Field label="Oppgave" name="title" required /><Select label="Type" name="type" value={type} onChange={(value) => setType(value as TaskType)} options={[{ value: "work", label: "Arbeidsoppgave" }, { value: "transport", label: "Transportoppdrag" }]} /><Select label="Status" name="status" options={statusOptions} /><Select label="Prioritet" name="priority" defaultValue="2" options={[{ value: "1", label: "1 (Lav)" }, { value: "2", label: "2 (Middels)" }, { value: "3", label: "3 (Høy)" }]} /><Select label="Hvem skal gjøre det" name="assignedUserId" required options={[{ value: "", label: "Velg person" }, ...data.users.map((user) => ({ value: String(user.id), label: `${user.name}${user.wannabeId ? ` · Wannabe ${user.wannabeId}` : ""}` }))]} /><Field label="Må gjøres innen" name="dueAt" type="datetime-local" required />{type === "transport" && <div className="md:col-span-2 lg:col-span-3"><Select label="Knytt til transportoppdrag" name="transportJobId" options={[{ value: "", label: "Ikke knyttet" }, ...data.transportJobs.map((job) => ({ value: String(job.id), label: `#${job.id} · ${shorten(job.description, 90)} · ${job.status}` }))]} /></div>}<label className="md:col-span-2 lg:col-span-3"><Label>Melding</Label><textarea name="message" maxLength={5000} className={textareaClass} placeholder="Melding fra personen som ønsker noe" /></label><label className="md:col-span-2 lg:col-span-3"><Label>Beskrivelse</Label><textarea name="description" minLength={5} maxLength={5000} required className={textareaClass} placeholder="Hva skal gjøres?" /></label></div><button disabled={saving} className={`${primaryButton} mt-5`}>{saving ? "Oppretter …" : "Opprett oppgave"}</button></form>;
}

function TaskList({ title, detail, tasks, accessToken, run, editable = false }: { title: string; detail: string; tasks: BifrostTask[]; accessToken: string; run: RunAction; editable?: boolean }) {
  return <div className={`${cardClass} mt-5`}><div className="flex items-end justify-between gap-4"><div><p className="text-sm text-slate-500">{detail}</p><h2 className="mt-1 text-xl font-semibold">{title}</h2></div><span className="rounded-full bg-white/5 px-3 py-1 text-xs text-slate-400">{tasks.length}</span></div>{tasks.length === 0 ? <EmptyState>Ingen oppgaver i denne listen.</EmptyState> : <div className="mt-5 grid gap-3">{tasks.map((task) => <TaskCard key={task.id} task={task} accessToken={accessToken} run={run} editable={editable} />)}</div>}</div>;
}

function TaskCard({ task, accessToken, run, editable }: { task: BifrostTask; accessToken: string; run: RunAction; editable: boolean }) {
  const [saving, setSaving] = useState(false);
  return <article className="rounded-xl border border-white/[.08] bg-black/10 p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-xs text-slate-600">#{task.id}</span><h3 className="font-medium text-slate-200">{task.title}</h3><Status status={task.status} /></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-400">{task.description}</p>{task.message && <div className="mt-3 rounded-lg border border-white/[.06] bg-white/[.025] p-3 text-sm text-slate-400"><span className="mb-1 block text-xs uppercase tracking-wider text-slate-600">Melding</span>{task.message}</div>}{task.transportJobId && <a href={`/transport?inspect=${task.transportJobId}`} className="mt-3 inline-block text-sm text-cyan-300">Transportoppdrag #{task.transportJobId}{task.transportDescription ? ` · ${shorten(task.transportDescription, 80)}` : ""}</a>}</div><div className="min-w-[220px] text-sm text-slate-500"><p>{typeLabel(task.type)} · {priorityLabel(task.priority)}</p><p className="mt-1">Tildelt: {task.assignedName}{task.assignedWannabeId ? ` · ${task.assignedWannabeId}` : ""}</p><p className="mt-1">Frist: {formatDate(task.dueAt)}</p><p className="mt-1 text-xs text-slate-600">Opprettet av {task.createdByName}</p></div></div>{editable && <form className="mt-4 flex flex-wrap items-end gap-2" onSubmit={(event) => { event.preventDefault(); const status = String(new FormData(event.currentTarget).get("status")) as TaskStatus; setSaving(true); void run(() => updateTaskStatus(accessToken, task.id, status), "Oppgavestatusen er oppdatert.").catch(() => undefined).finally(() => setSaving(false)); }}><div className="min-w-[190px]"><Select label="Endre status" name="status" defaultValue={task.status} options={statusOptions} /></div><button disabled={saving} className={secondaryButton}>{saving ? "Lagrer …" : "Lagre status"}</button></form>}</article>;
}

function Select({ label, options, onChange, ...props }: { label: string; name: string; options: Array<{ value: string; label: string }>; required?: boolean; defaultValue?: string; value?: string; onChange?: (value: string) => void }) { return <label><Label>{label}</Label><select {...props} onChange={onChange ? (event) => onChange(event.target.value) : undefined} className={selectClass}>{options.map((option) => <option key={`${option.value}:${option.label}`} value={option.value}>{option.label}</option>)}</select></label>; }
function Field({ label, ...props }: { label: string; name: string; type?: string; required?: boolean }) { return <label><Label>{label}</Label><input {...props} className={inputClass} /></label>; }
function Label({ children }: { children: string }) { return <span className="mb-2 block text-sm text-slate-400">{children}</span>; }
function Status({ status }: { status: TaskStatus }) { const classes = status === "completed" ? "bg-emerald-300/10 text-emerald-200" : status === "blocked" ? "bg-rose-300/10 text-rose-200" : status === "in_progress" ? "bg-violet-300/10 text-violet-200" : "bg-slate-300/10 text-slate-300"; return <span className={`rounded-full px-2.5 py-1 text-xs ${classes}`}>{statusLabel(status)}</span>; }
function Banner({ tone, children }: { tone: "success" | "error"; children: string }) { return <div className={`mb-5 rounded-xl border px-4 py-3 text-sm ${tone === "success" ? "border-emerald-300/20 bg-emerald-300/10 text-emerald-200" : "border-rose-400/20 bg-rose-400/10 text-rose-200"}`}>{children}</div>; }
function EmptyState({ children }: { children: string }) { return <p className="mt-5 rounded-xl border border-dashed border-white/10 px-5 py-8 text-center text-sm text-slate-600">{children}</p>; }
function WorkspaceState({ title, detail, error = false }: { title: string; detail: string; error?: boolean }) { return <section className="grid flex-1 place-items-center py-16"><div className="text-center"><p className={error ? "text-rose-300" : "text-cyan-300"}>{error ? "Feil" : "Vent litt"}</p><h1 className="mt-2 text-2xl font-semibold">{title}</h1><p className="mt-2 text-slate-500">{detail}</p></div></section>; }
function statusLabel(status: TaskStatus) { return { not_started: "Ikke startet", in_progress: "Pågår", blocked: "Blokkert", completed: "Ferdig" }[status]; }
function typeLabel(type: TaskType) { return type === "transport" ? "Transportoppdrag" : "Arbeidsoppgave"; }
function priorityLabel(priority: TaskPriority) { return priority === 1 ? "Lav" : priority === 3 ? "Høy" : "Middels"; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString("nb-NO", { dateStyle: "short", timeStyle: "short" }); }
function shorten(value: string, length: number) { return value.length > length ? `${value.slice(0, length - 1)}…` : value; }
function messageFrom(reason: unknown) { return reason instanceof Error ? reason.message : "Handlingen kunne ikke fullføres."; }

type RunAction = (action: () => Promise<unknown>, message: string) => Promise<void>;
const statusOptions = [{ value: "not_started", label: "Ikke startet" }, { value: "in_progress", label: "Pågår" }, { value: "blocked", label: "Blokkert" }, { value: "completed", label: "Ferdig" }];
const cardClass = "rounded-2xl border border-white/10 bg-white/[.025] p-5";
const inputClass = "w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 outline-none focus:border-cyan-300/60";
const selectClass = "w-full rounded-xl border border-white/10 bg-[#0b1724] px-3 py-2.5 outline-none focus:border-cyan-300/60";
const textareaClass = `${inputClass} min-h-24`;
const primaryButton = "rounded-xl bg-cyan-300 px-5 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-50";
const secondaryButton = "rounded-xl border border-white/10 px-4 py-2.5 text-sm text-slate-300 hover:bg-white/5 disabled:opacity-50";
